try:
    raise Exception("error 1")
except Exception as e:
    print(e)
